export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CLUB_EVENT_REPOSITORY = 'CLUB_EVENT_REPOSITORY';
export const DJ_REPOSITORY = 'DJ_REPOSITORY';
export const SOCIAL_MEDIA_REPOSITORY = 'SOCIAL_MEDIA_REPOSITORY';
